#Based on https://github.com/sPooKee/umbrel-community-app-store
version: '3.8'

services:

  app_proxy:
    environment:
      # The format here is: <app-id>_<docker-service-name>_1
      APP_HOST: tommy-grafana_grafana_1
      APP_PORT: 3000

  grafana:
    image: grafana/grafana:6.0.1
    container_name: surrealdb-grafana
    user: "0"
    environment:
      GF_LOG_LEVEL: error
      GF_PATHS_PROVISIONING: /etc/grafana/provisioning
      GF_PATHS_CONFIG: /etc/grafana/grafana.ini
    volumes:
      - "${APP_DATA_DIR}/config/grafana:/etc/grafana"
      - "${APP_DATA_DIR}/config/dashboards:/tmp/dashboards"
      - "${APP_DATA_DIR}/data/grafana:/var/lib/grafana"
    extra_hosts:
      - "host.docker.internal:host-gateway"
