version: '3'
services:
  app_proxy:
    environment:
      # The format here is: <app-id>_<docker-service-name>_1
      APP_HOST: tommy-drone_drone_1
      APP_PORT: 80
  runner:
    image: drone/drone-runner-docker:1
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_RPC_PROTO=http
      - DRONE_RPC_HOST=${DEVICE_DOMAIN_NAME}
      - DRONE_RPC_SECRET=super-duper-secret
      - DRONE_RUNNER_CAPACITY=2
      - DRONE_RUNNER_NAME=umbrel-drone

  drone:
    image: drone/drone:2
    restart: always
    volumes:
      - /var/lib/drone:/data
    environment:
      - DRONE_GITHUB_CLIENT_ID=your-id
      - DRONE_GITHUB_CLIENT_SECRET=super-duper-secret
      - DRONE_RPC_SECRET=super-duper-secret
      - DRONE_SERVER_HOST=${DEVICE_DOMAIN_NAME}
      - DRONE_SERVER_PROTO=http